api: yes
apiAddress: :9997

hls: yes
hlsAddress: :8888
hlsAllowOrigin: "*"
hlsVariant: mpegts
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentCount: 7

webrtc: yes
webrtcAddress: :8889
webrtcICEHostNAT1To1IPs:
  - MEDIAMTX_IP_ADDRESS

webrtcICEUDPMuxAddress: :8189

webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

authInternalUsers:
  - user: MEDIAMTX_PUBLISH_USER
    pass: MEDIAMTX_PUBLISH_PASS
    ips: []
    permissions:
      - action: publish
        path: MEDIAMTX_PUBLISH_PATH
      - action: api
  - user: any
    pass:
    ips: []
    permissions:
      - action: read
        path: MEDIAMTX_PUBLISH_PATH

paths:
  MEDIAMTX_PUBLISH_PATH:
    source: publisher